module.exports = {
    baoming:{
        css:"div.act-item-rt.clear-fix>ul:nth-child(4)>li:nth-child(1)"
    },
    uploadpic:{
        css:"div:nth-child(1)>div>div>div.ivu-col.ivu-col-span-12>div>div.upload-img.ivu-upload"
    },
    shopid:{
        css:"div.form-item-13.ivu-form-item.ivu-form-item-required>div>div>div.ivu-col.ivu-col-span-12"
    },
    liyidian:{
        css:"div.form-item-1.ivu-form-item.ivu-form-item-required>div>div>div.ivu-col.ivu-col-span-12"
    },
    doudipic:{
        css:"div:nth-child(4)>div>div>div.ivu-col.ivu-col-span-12>div>div.upload-img.ivu-upload"
    },
    submit:{
        css:"div.enroll-submit>button"
    },
    resubmit:{
        css:"button.qr.ivu-btn.ivu-btn-primary.ivu-btn-large"
    } 
}